# Configuración de Build para Netlify
[build]
  command = "node set-env.js && ng build --configuration production"
  publish = "dist/frontend"

# Redirección para Single Page Applications (SPA) como Angular
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200